### PR TITLE
Releasing 0.10.1

### PR DESCRIPTION
**Pull request by yuce**

### CODE REVIEW

**Comment by nalundgaard** [comment]
Hi, can you please push a git tag for 0.10.1 as well, so that we can pin to that in rebar 2.X projects that do not support Hex.pm?

**Comment by nalundgaard** [comment]
also, aside, this probably should have been a 1.0.0 release, because renaming one of the modules is not backwards-compatible. 0.9.8 -> 0.10.1 doesn't suggest backwards-incompatible change in the semantic versioning scheme.

**Comment by yuce** [comment]
OK, I'll push a tag for this release if you promise to star the project.

I think releases with `0` as the major version are more relaxed with versioning wrt breaking changes.

**Comment by nalundgaard** [comment]
Done, and good point. I agree 100%. Thanks!

**Comment by yuce** [comment]
Thanks, the tag lives!

**Pull request merged**
