### PR TITLE
Migrate from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by nalundgaard**
travis-ci.org is shut down and no longer operating. Let's use GitHub Actions instead.

### CODE REVIEW

**Comment by nalundgaard** [comment]
@yuce I can't quite understand why [20.3.x](https://github.com/yuce/pot/runs/2046761561?check_suite_focus=true) fails, looks like some strange TLS issue:

> ===> Running coveralls...
> rebar_coveralls:Exporting cover data from _build/test/cover/eunit.coverdata using service github and jobid 627524289
> Analysis includes data from imported files
> ["/__w/pot/pot/_build/test/cover/eunit.coverdata"]
> Analysis includes data from imported files
> ["/__w/pot/pot/_build/test/cover/eunit.coverdata"]
> 
> =INFO REPORT==== 6-Mar-2021::15:34:51 ===
> TLS client: In state cipher received SERVER ALERT: Fatal - Bad Record MAC
> 
> ===> Uncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump
> ===> When submitting a bug report, please include the output of `rebar3 report "your command"`
> make: *** [coveralls] Error 1
> Makefile:18: recipe for target 'coveralls' failed

**Comment by nalundgaard** [comment]
Here's the full error with `DIAGNOSTIC=1`. I guess it is an issue with 20.3 not liking coveralls.io's HTTPS certificate:

> ```
> ===> Uncaught error: {badmatch,
>                          {error,
>                              {failed_connect,
>                                  [{to_address,{"coveralls.io",443}},
>                                   {inet,
>                                       [inet],
>                                       {tls_alert,"bad record mac"}}]}}}
> ===> Stack trace to the error location:
> [{coveralls,send,2,
>             [{file,"/__w/pot/pot/_build/default/plugins/coveralls/src/coveralls.erl"},
>              {line,113}]},
>  {rebar3_coveralls,do_coveralls,5,
>                    [{file,"/__w/pot/pot/_build/default/plugins/coveralls/src/rebar3_coveralls.erl"},
>                     {line,152}]},
>  {rebar3_coveralls,do,1,
>                    [{file,"/__w/pot/pot/_build/default/plugins/coveralls/src/rebar3_coveralls.erl"},
>                     {line,71}]},
>  {rebar_core,do,2,
>              [{file,"/usr/src/rebar3-src/src/rebar_core.erl"},{line,155}]},
>  {rebar_prv_do,do_task,5,
>                [{file,"/usr/src/rebar3-src/src/rebar_prv_do.erl"},{line,87}]},
>  {rebar_core,do,2,
>              [{file,"/usr/src/rebar3-src/src/rebar_core.erl"},{line,155}]},
>  {rebar_prv_do,do_task,5,
>                [{file,"/usr/src/rebar3-src/src/rebar_prv_do.erl"},{line,87}]},
>  {rebar_core,do,2,
>              [{file,"/usr/src/rebar3-src/src/rebar_core.erl"},{line,155}]}]
> ===> When submitting a bug report, please include the output of `rebar3 report "your command"`
> make: *** [coveralls] Error 1
> Makefile:18: recipe for target 'coveralls' failed
> Error: Process completed with exit code 2.
> ```

**Review by yuce — CHANGES_REQUESTED** [review]
Thanks @nalundgaard, it looks good, except, could you quote the strings in the YAML file?

**Review by yuce — APPROVED** [review]
Thanks!

**Pull request merged**
