### PR TITLE
updated README; updated CONTRIBUTORS; bumped the version

### PR DESCRIPTION
**Pull request by nalundgaard**
Releasing https://github.com/yuce/pot/pull/25.

### CODE REVIEW

**Comment by nalundgaard** [comment]
@yuce if you want to add me to the repo on Hex, I can also publish new releases. [This](https://hex.pm/users/nalundgaard) is me on Hex.

**Comment by yuce** [comment]
@nalundgaard  Thanks for this! I'll release v1 next week and then I'll add you as a/the publisher on hex. Would that be OK?

**Review by yuce — APPROVED** [review]

**Comment by nalundgaard** [comment]
Sounds great! Thanks!

**Comment by nalundgaard** [comment]
Sounds great! Thanks!

**Pull request merged**
